import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { acme, inter, oswald } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${oswald.variable} ${acme.variable}`}>
      <body>
        <Navbar />        {/* Always stays here */}
        <main>{children}</main> {/* This is where page.tsx content appears */}
        <Footer />        {/* Always stays here */}
      </body>
    </html>
  );
}
